import Head from "next/head"
import styles from "../styles/Home.module.css"
import LandingPage from "../components/LandingPage"
import ProfileCard from "../components/ProfileCard"
import DarkButton from "../components/DarkMode"
import axios from "axios"
import { useEffect, useState } from "react"
import NaviBar from "../components/NaviBar"

export default function Home() {
  const [getProfile, setProfile] = useState([])
  const [getUtils, setUtils] = useState([])
  useEffect(() => {
    axios.get("/api/utils").then((result) => {
      setUtils(result.data)
    })
    axios.get("/api/profile").then((result) => {
      setProfile(result.data)
    })
  }, [])

  return (
    <div>
      <NaviBar />
      <div className={styles.container}>
        <Head>
          <title>{getProfile.name} Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.main}>
          <LandingPage profile={getProfile} utils={getUtils} />
        </div>
        <div className={styles.profile}>
          <ProfileCard profile={getProfile} utils={getUtils} />
        </div>
        <div className={styles.modeButton}>
          <DarkButton />
        </div>
      </div>
    </div>
  )
}
